import { DBCollege, DBCourse, DBPlacement, DBRanking } from '../schema';

export const SEED_COLLEGES: DBCollege[] = [
  {
    id: 'col-1',
    name: 'Indian Institute of Technology Bombay (IIT Bombay)',
    slug: 'iit-bombay',
    shortName: 'IITB',
    establishmentYear: 1958,
    ownership: 'Government',
    approvalStatus: ['UGC', 'AICTE', 'Autonomous'],
    naacGrade: 'A++',
    location: {
      address: 'Main Gate Road, Powai',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400076',
      country: 'India',
      coordinates: { lat: 19.1334, lng: 72.9133 },
    },
    contact: {
      website: 'https://www.iitb.ac.in',
      email: 'info@iitb.ac.in',
      phone: '+91-22-2572-2545',
      admissionHelpline: '+91-22-2576-7000',
    },
    overview: 'Indian Institute of Technology Bombay is a premier public technical research university located in Powai, Mumbai. Recognized as an Institute of Eminence, IIT Bombay is famous for world-class engineering programs, cutting-edge innovation labs, and strong global placements.',
    highlights: [
      'Ranked #1 Engineering Institute by NIRF',
      'Institute of Eminence (IoE) status by Govt of India',
      'State-of-the-art incubation centre (SINE)',
      '100% Placement Record for B.Tech Core Branches',
    ],
    facilities: [
      { icon: 'Library', name: 'Central Library', description: 'Over 500,000 volumes, e-journals & digital repositories' },
      { icon: 'Wifi', name: 'Campus Wi-Fi', description: 'High-speed 10 Gbps fiber network across campus & hostels' },
      { icon: 'Home', name: 'Hostel Facilities', description: '18 student hostels with modern dining and recreation' },
      { icon: 'Cpu', name: 'Supercomputing Lab', description: 'Advanced GPU clusters for AI/ML and research computation' },
    ],
    faculty: [
      { id: 'f-1', name: 'Dr. Subhasis Chaudhuri', designation: 'Professor & Director', department: 'Electrical Engineering', qualification: 'Ph.D. (UCSD)' },
      { id: 'f-2', name: 'Dr. Pushpak Bhattacharyya', designation: 'Professor', department: 'Computer Science', qualification: 'Ph.D. (IIT Bombay)' },
    ],
    gallery: [
      { id: 'g-1', url: 'https://images.unsplash.com/photo-1562774053-701939374585', caption: 'IIT Bombay Campus Gate', category: 'Campus' },
    ],
    documents: [
      { id: 'doc-1', title: 'IIT Bombay Information Brochure 2026', url: '/brochures/iit-bombay.pdf', fileType: 'pdf' },
    ],
    featured: true,
    isVerified: true,
    rating: 4.9,
    reviewCount: 342,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-07-21T00:00:00Z',
  },
  {
    id: 'col-2',
    name: 'Indian Institute of Management Ahmedabad (IIM Ahmedabad)',
    slug: 'iim-ahmedabad',
    shortName: 'IIMA',
    establishmentYear: 1961,
    ownership: 'Government',
    approvalStatus: ['UGC', 'EQUIS', 'AACSB'],
    naacGrade: 'A++',
    location: {
      address: 'Vastrapur',
      city: 'Ahmedabad',
      state: 'Gujarat',
      pincode: '380015',
      country: 'India',
      coordinates: { lat: 23.0333, lng: 72.5300 },
    },
    contact: {
      website: 'https://www.iima.ac.in',
      email: 'admission@iima.ac.in',
      phone: '+91-79-6632-3456',
    },
    overview: 'IIM Ahmedabad is India’s premier management institution, consistently ranked #1 in management education. Renowned for its rigorous case-study methodology, world-renowned faculty, and unmatched leadership pipeline.',
    highlights: [
      'NIRF #1 Management Institute in India',
      'EQUIS Accredited Business School',
      'Highest international placement packages',
    ],
    facilities: [
      { icon: 'BookOpen', name: 'Vikram Sarabhai Library', description: 'Asia’s top management research library' },
      { icon: 'Coffee', name: 'Louis Kahn Plaza', description: 'Iconic architectural hub for student events' },
    ],
    faculty: [
      { id: 'f-3', name: 'Dr. Bharat Bhasker', designation: 'Director', department: 'Information Systems', qualification: 'Ph.D. (VPI & SU)' },
    ],
    gallery: [],
    documents: [],
    featured: true,
    isVerified: true,
    rating: 4.95,
    reviewCount: 289,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-07-21T00:00:00Z',
  },
  {
    id: 'col-3',
    name: 'Birla Institute of Technology and Science (BITS Pilani)',
    slug: 'bits-pilani',
    shortName: 'BITS',
    establishmentYear: 1964,
    ownership: 'Private',
    approvalStatus: ['UGC', 'AICTE', 'Deemed'],
    naacGrade: 'A',
    location: {
      address: 'Vidya Vihar Campus',
      city: 'Pilani',
      state: 'Rajasthan',
      pincode: '333031',
      country: 'India',
    },
    contact: {
      website: 'https://www.bits-pilani.ac.in',
      email: 'admissions@pilani.bits-pilani.ac.in',
      phone: '+91-1596-242192',
    },
    overview: 'BITS Pilani is a top-ranked private deemed university known for its merit-based admission via BITSAT, zero-attendance policy option, and 6-month Practice School industry internship program.',
    highlights: [
      'Top Tier Private Engineering Institute',
      '6-Month Mandatory Practice School Internship',
      'Strong Global Alumni Network',
    ],
    facilities: [
      { icon: 'Briefcase', name: 'Practice School Cell', description: 'Industry exposure with 400+ corporate partners' },
    ],
    faculty: [],
    gallery: [],
    documents: [],
    featured: true,
    isVerified: true,
    rating: 4.8,
    reviewCount: 215,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-07-21T00:00:00Z',
  },
];

export const SEED_COURSES: DBCourse[] = [
  {
    id: 'crs-1',
    collegeId: 'col-1',
    title: 'B.Tech in Computer Science & Engineering',
    slug: 'btech-computer-science-iit-bombay',
    code: 'BTECH-CSE',
    degreeLevel: 'Undergraduate',
    stream: 'Engineering',
    durationYears: 4,
    mode: 'Full Time',
    tuitionFeeTotal: 800000,
    tuitionFeePerYear: 200000,
    currency: 'INR',
    eligibility: '10+2 with Physics, Chemistry & Mathematics + JEE Advanced rank under top 70',
    acceptedExams: ['JEE Advanced'],
    seatIntake: 180,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-07-21T00:00:00Z',
  },
  {
    id: 'crs-2',
    collegeId: 'col-2',
    title: 'Post Graduate Program in Management (MBA/PGP)',
    slug: 'pgp-mba-iim-ahmedabad',
    code: 'PGP-MBA',
    degreeLevel: 'Postgraduate',
    stream: 'Management',
    durationYears: 2,
    mode: 'Full Time',
    tuitionFeeTotal: 2500000,
    tuitionFeePerYear: 1250000,
    currency: 'INR',
    eligibility: 'Bachelor degree with min 50% + CAT score (99+ percentile) + WAT/PI',
    acceptedExams: ['CAT', 'GMAT'],
    seatIntake: 385,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-07-21T00:00:00Z',
  },
];

export const SEED_PLACEMENTS: DBPlacement[] = [
  {
    id: 'plc-1',
    collegeId: 'col-1',
    year: 2025,
    highestPackageLPA: 168.0,
    averagePackageLPA: 24.5,
    medianPackageLPA: 20.0,
    placementPercentage: 96.5,
    topRecruiters: [
      { name: 'Google' },
      { name: 'Microsoft' },
      { name: 'Apple' },
      { name: 'Goldman Sachs' },
      { name: 'Qualcomm' },
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-07-21T00:00:00Z',
  },
];

export const SEED_RANKINGS: DBRanking[] = [
  {
    id: 'rnk-1',
    collegeId: 'col-1',
    agency: 'NIRF',
    rank: 1,
    category: 'Engineering',
    year: 2025,
    score: 89.5,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-07-21T00:00:00Z',
  },
  {
    id: 'rnk-2',
    collegeId: 'col-2',
    agency: 'NIRF',
    rank: 1,
    category: 'Management',
    year: 2025,
    score: 84.2,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-07-21T00:00:00Z',
  },
];
